### ISSUE TITLE
New paths for VSTs in UAD 10.1.0

### ISSUE THREAD

**Issue by alecvance** [jondkinney/UAD-Hide-And-Seek-Script#14]
it seems that Universal Audio has organized the plugins in the VST folders by category, such that the pathnames no longer work. 

For example: `/Library/Audio/Plug-Ins/VST/Universal Audio/Channel Strip and Preamp/UAD Neve 1073.vst`

**Comment by jondkinney** [comment]
Well that's fun. I guess I'll have to take a crack at updating the giant case statement and re-work it to be something more maintainable.

**Comment by jondkinney** [comment]
@alecvance I'm working on revisions that address these issues. So far I have it working for UAD-2 plugins in the VST and VST3 folders. Need to ensure that the UADx instances will move as well. The folder structures (and names) are different between the two technologies...so it's going to take a good bit of refactoring and conditional logic. But the good news is that I have it about 50% done, and I have a JSON object now instead of that ridiculous case statement. Stay tuned!

**Comment by alecvance** [comment]
That’s great to hear.

**Comment by jondkinney** [comment]
@alecvance Alright, this is finally complete and works with the new nested folder structure! I also migrated the case statement to a JSON file that will be easier to maintain separately from the code.

**Comment by alecvance** [comment]
This is working great now, thanks so much!
